### ISSUE TITLE
Comma Usage

### ISSUE THREAD

**Issue by StoneyJackson** [wne-csit-jackson/cs220-sp2024-FarmData2#15]
Correct the comma usage in the sentence "If you are unfamiliar with one or more of these technologies the ONBOARDING document provides additional information about each, as well as resources and activities for learning about them." that appears at the end of the "Technology Onboarding" section of the `CONTRIBUTING.md` document.

Add a comma between "technologies" and "the ONBOARDING"
Remove the comma between "about each" and "as well as"

**Comment by AirportHobo21** [comment]
I would like to work on this please!
