### ISSUE TITLE
Make Update plural

### ISSUE THREAD

**Issue by StoneyJackson** [wne-csit-jackson/cs220-sp2024-FarmData2#16]
Change "Update" to "Updates" in the phrase "Update to any of the FarmData2 documentation are welcome." in the first sentence of the "Documentation" section of the `CONTRIBUTING.md` file.

**Comment by MAhlman** [comment]
I would like to work on this please!

**Comment by StoneyJackson** [comment]
@MAhlman in the future, be sure not to put any extra word between "Fixes" and the issue number "#16"... so, you want... "Fixes #16"
