### ISSUE TITLE
Fix Italics

### ISSUE THREAD

**Issue by StoneyJackson** [wne-csit-jackson/cs220-sp2024-FarmData2#8]
Change  "_spec_s" to "\*spec\*s" at the end of the sentence "A test typically consists of a series of steps that are automated by the Cypress tests, called _spec_s." in the "End-to-End Tests" section under the "Cypress" heading in the`ONBOARDING.md` file. 

Note: The _spec_s or \*spec\*s is supposed to make the *spec* appear in italics.  However, it turns out that \* works within a word but \_ does not.

**Comment by Aaron13632** [comment]
I would like to work on this please!
